spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_blog
    username: proxidev
    password: proxidev
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8000
